### ISSUE TITLE
[Feature] Allow a different list of tags to be used for post tags 

### ISSUE THREAD

**Issue by christopherpickering** [quasibit/eleventy-plugin-schema#16]
Right now the post is limited to use the tags specified on the font mater `tags`, but it would be nice to allow other tags to be used.

For example an override in the meta:

```yaml
meta:
   tags:
     - tag 1
     - tag 2
```
